name: Embedded Actions
description: Reusable composite action.

inputs:
  var_01:
    required: false
    description: var_01 
  var_02:
    required: false
    description: var_02
    default: "var_02 default"

runs:
  using: "composite"
  steps:
    - name: Echo ing
      run: |
        echo "var_01: '${{ inputs.var_01 }}'"
        echo "var_02: '${{ inputs.var_02 }}'"
