name: Create PR
on:
  push:
    branches:
      - gitops
    paths:
      - 'prod/**'
jobs:
  create-PR:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gitops
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: create pull request
      id: open-pr
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ github.token }}
        destination_branch: ${{ github.event.repository.default_branch }}
        pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
        pr_body: "Automated Pull Request"
        pr_reviewer: "louise-x"
        pr_assignee: "louise-x"
    - name: enable automerge
      if: steps.open-pr.outputs.pr_number != ''
      uses: peter-evans/enable-pull-request-automerge@v2
      with:
        token: ${{ github.token }}
        pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
        merge-method: merge