name: Lint PR
on:
  # pull_request:
  #   types: ['opened', 'edited', 'reopened', 'synchronize']
  pull_request:
    types:
      - closed
    branches:
      - main
    
jobs:
  merge-main-back-to-trunk:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gitops
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: Merge main back to trunk
      run: |
          git fetch origin main
          git merge -X ours origin/main --allow-unrelated-histories -m "Auto-merge main to gitops"
          git push -u origin HEAD --verbose -f 
update-values:
  if: github.event.pull_request.merged == true
  needs: merge-main-back-to-trunk
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: gitops
    - name: Update deployment.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: "kubernetes/${{ env.ENV_SHORT }}/deployment.yaml"
        propertyPath: "spec.template.spec.containers[0].image"
        value: "${{ env.AWS_ACCOUNT }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
        message: "release deployment image tag: ${{ github.sha }}"
        branch: ${{ github.event.pull_request.head.ref }}
        createPR: false
        title: "Release ${{ env.ENV_LONG }} with deployment image tag"
