name: lint

'on':
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - test-pr

jobs:
  cookstyle:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.3
        bundler-cache: true
    - uses: r7kamura/rubocop-problem-matchers-action@v1 # this shows the failures in the PR
    - run: gem install Cookstyle -v 7.31.1
    - run: cookstyle -v