name: Multiple-Env

on:
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - 'main'
  push:
    branches:
      - '12-main'

jobs:
  job-env-01:
    runs-on: ubuntu-latest
    environment:
      name: env-01
    steps:
      - name: Job in Env-01
        run: |
          echo "env vars: '${{ vars.ENV_ID }}'"
          
  job-env-02:
    runs-on: ubuntu-latest
    needs: job-env-01
    environment:
      name: env-02
    steps:
      - name: Job in Env-02
        run: |
          echo "env vars: '${{ vars.ENV_ID }}'"
