name: Promote Prod Ver Workflow

on:
  workflow_dispatch: # Putting here is also fine!!

jobs:
  promote-stg-to-prod:
    # if: ${{ startsWith(github.ref, 'refs/heads/release/R') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
    - name: promote stg to prod
      run: |
        git checkout origin/gitops -- stg-value.yaml
        cp stg-value.yaml prod-value.yaml
        git add .
        git diff-index --quiet HEAD || git commit -m "promote prod `git log -1 --pretty=format:'%s' origin/gitops -- stg-value.yaml`"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ github.token }}
        commit-message: promote stg to prod
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: promote-prod
        delete-branch: false
        title: '[Example] promote stg to prod'
        body: |
          promote stg to prod
          - Updated with *today's* date
          - Auto-generated by [create-pull-request][1]
        assignees: ${{ github.actor }}
        reviewers: louise-x
        draft: false