name: Test Release Branch Create

on: 
  create:

jobs:
  release-branch-workflow:
    if: ${{ startsWith(github.ref, 'refs/heads/release/R') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Git config
      env:
        BRANCH:  ${{ github.head_ref || github.ref_name }}
      run: |
          git status
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          echo "branch name tranfer to: ${BRANCH//\//-}"