name: Show Me the S3cr3tz
on:
  workflow_dispatch:
  # push:

jobs:
  debug:
    name: Debugging
    runs-on: ubuntu-latest
    steps:
    - name: Set up secret file
      env:
        CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET}}
      run: |
        echo "CLIENT ID"
        echo ${{secrets.CLIENT_ID}} | sed 's/./& /g'
        echo "TS_OAUTH_SECRET"
        echo ${{secrets.TS_OAUTH_SECRET}} | sed 's/./& /g'