name: Sync-And-Update-Gitops
on:
  push:
    branches:
      - main
  # pull_request:
  #   types: ['opened', 'edited', 'reopened', 'synchronize']
  pull_request:
    types:
      - closed
    branches:
      - main
    
jobs:
  merge-main-back-to-gitops:
    # if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gitops
    - name: Set Git config
      run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions "
          git config --local pull.ff true
    # - name: Sync main to gitops
    #   run: |
    #       git fetch origin main
    #       git reset --hard origin/main
    #       git checkout origin/gitops -- stg-value.yaml
    #       git add stg-value.yaml
    #       git status
    #       git diff-index --quiet HEAD || git commit -m "`git log -1 --pretty=format:'%s' origin/gitops -- stg-value.yaml`"
    - name: Alternative merge
      run: |
        git fetch origin main
        git checkout main
        git merge --allow-unrelated-histories gitops
    - name: Debugging
      run: |
          git push -u origin gitops -f
    # - name: Merge main -> gitops
    #   uses: devmasx/merge-branch@master
    #   with:
    #     type: now
    #     from_branch: main
    #     target_branch: gitops
    #     message: Merge main into gitops
    #     github_token: ${{ secrets.GITHUB_TOKEN }}

  update-values:
    # if: github.event.pull_request.merged == true
    needs: merge-main-back-to-gitops
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gitops
      - name: Update deployment.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "version.yml"
          propertyPath: "images[0].newTag"
          value: "${{ github.ref_name }}-${{ github.sha }}"
          message: "Update image tag: ${{ github.ref_name }}-${{ github.sha }}"
          createPR: false
          title: "Update gitops image tag"
          # targetBranch: gitops
          branch: gitops
          masterBranchName: main
          commitChange: true
          description: |
            Update image tag: ${{ github.ref_name }}-${{ github.sha }} Desc
