name: TestTailscale
on:
  workflow_dispatch:

jobs:
  deploy-via-tailscale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        tags: tag:ci
    - name: Test Conn
      run: |
        ping -c 5 172.20.0.16
        echo "check chef infra conn"
        nc -zv 172.20.0.212 443
        echo "check ns server conn"
        nc -zv 172.20.0.2 53
        echo "check cross vpc conn"
        nc -zv 172.31.30.103 22