name: Actions-by-BranchCut

on: 
  create
    branches:
      - "release/R*"
jobs:
  check-if-branchcut:
    if: ${{ startsWith(github.ref, 'refs/heads/release/R') }}
    runs-on: ubuntu-latest
    steps:
    - name: Set Git config
      run: echo "branch cut occurred ${GITHUB_REF}"
      