name: Actions-by-BranchCut

on: create

jobs:
  check-if-branchcut:
    if: ${{ contains(github.ref, 'refs/heads/releases/') }}
    runs-on: ubuntu-latest
    steps:
    - name: Set Git config
      run: echo "branch cut occurred $github.ref"