name: GH-Actions-Basic

on:
  push:
    branches:
      - main

jobs:
  read-env:
    runs-on: ubuntu-latest
    environment:
      name: env-01
    steps:
      - name: Read Env vars
        run: |
          echo "env vars: '${{ vars.ENV_ID }}'"
