name: GH-Receiver
 
on:
  repository_dispatch:
    types: [some_event]
 
jobs:
  receiver:
    runs-on: ubuntu-latest
    steps:
      - name: A event received
        run: |
          echo "payload Foo '${{ github.event.client_payload.foo }}'"
      - uses: actions/checkout@v4
        name: check-local-files
        with:
          fetch-depth: 0
        run: |
          pwd && ls -al .
      - uses: actions/checkout@master
        with:
          name: louise-x/argocd-demo
          ref: refs/heads/main
          path: 'destination_folder'
          sparse-checkout: 'proj-b'
          sparse-checkout-cone-mode: false
          # token: ${{ secrets.my_pat }}   for private repo
        run: |
          echo "current folder state"
          ls -al .
          ls -al destination_folder
# sync source repo folder
# update field
# create PR
# merge PR
# case 1: src repo folder: add file
# case 2: src repo folder: remove file
# case 3: src repo folder: dest new folder