name: GH-Actions-Basic

on:
  push:
    branches:
      - main
      - 'release/R*'
  workflow_dispatch:
    inputs:
      request_name:
        description: Trigger request
        required: false
        default: "test"

jobs:
  set-envs:
    outputs:
      deploy-branch: ${{ steps.set-envs.outputs.deploy_branch }}
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.request_name }} == 'test' 
    environment:
      name: env-01
    steps:
      - name: Check branch
        id: set-envs
        run: |
          if ${{ startsWith(github.ref, 'refs/heads/release/R') }}; then
            echo "deploy_branch=release" >> $GITHUB_OUTPUT
            echo "branch is ${{ github.ref }}"
          else
            echo "deploy_branch=main" >> $GITHUB_OUTPUT
            echo "main"
          fi
          
  read-env:
    runs-on: ubuntu-latest
    needs: set-envs
    environment:
      name: env-01
    if: github.ref == 'refs/heads/main' && ${{ github.event.inputs.request_name }} != 'test' 
    steps:
      - name: Read Env vars
        run: |
          echo "env vars: '${{ vars.ENV_ID }}'"
          echo "branch is ${{ needs.set-envs.outputs.deploy-branch }}"
      # - name: Invoke Embedded Actions
      #   uses: ./.github/actions/echo
      #   with:
      #     var_01: "test---01"
      #     var_02: "test---02"
  
  read-env-release:
    runs-on: ubuntu-latest
    needs: set-envs
    environment:
      name: env-01
    if: startsWith(github.ref, 'refs/heads/release/R') && ${{ github.event.inputs.request_name }} != 'test' 
    steps:
      - name: Read Env vars
        run: |
          echo "job is  read-env-release "
          echo "branch is ${{ needs.set-envs.outputs.deploy-branch }}"
  
  react:
    runs-on: ubuntu-latest
    needs: read-env
    if: ${{ github.event.inputs.request_name }} == 'test' 
    steps:
      - name: Check inputs
        run: |
          echo "got input request test"